<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "snet_tmpl_basic"
 *
 * Auto generated by Extension Builder 2013-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SNET Basic Template',
	'description' => 'The Basic Template Extension for TYPO3 sites made by STIMME.NET',
	'category' => 'distribution',
	'author' => 'Andreas Beyl',
	'author_email' => 'beyl@stimme.net',
	'author_company' => 'STIMME.NET - Heilbronner Stimme GmbH und Co. KG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
			'version' => '7.6',
			'additional_reports' => '2.6.9',
			'gridelements' => '3.0.0',
			'news' => '3.0.1',
			'realurl' => '1.12.8',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
