<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "snet_tmpl_basic"
 *
 * Auto generated by Extension Builder 2013-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SNET Basic Template',
	'description' => 'The Basic Template Extension for TYPO3 sites made by STIMME.NET',
	'category' => 'plugin',
	'author' => 'Andreas Beyl',
	'author_email' => 'beyl@stimme.net',
	'author_company' => 'STIMME.NET - Heilbronner Stimme GmbH und Co. KG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'phpunit' => '3.7.22',
			'extension_builder' => '2.5.2',
			't3adminer' => '1.3.1',
			'additional_reports' => '2.6.6',
			'cron_setdefaultauthor' => '0.1.0',
			'fl_seo_sitemap' => '0.2.0',
			'gridelements' => '2.0.2',
			'news' => '2.3.0',
			'realurl' => '1.12.8',
			'scriptmerger' => '4.0.3',
			'tq_seo' => '6.0.1',
			'wt_spamshield' => '1.1.1'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
