### Hinweis fuer <=IE7-Benutzer ###
#################################
[browser = msie] && [version = <7, =7]
    lib.oldIE = HTML
    lib.oldIE.value = <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'><div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div><div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'><div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='Warning!'/></div><div style='width: 275px; float: left; font-family: Arial, sans-serif;'><div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>Sie benutzen einen alten Browser</div><div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>Um diese Seite besser nutzen und betrachten<br />zu k&ouml;nnen, aktualisieren Sie bitte Ihren Browser.</div></div><div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank' title='Get current Firefox'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get current Firefox' /></a></div><div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank' title='Get current Internet Explorer' ><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get current Internet Explorer' /></a></div><div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank' title='Get current Safari'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get current Safari' /></a></div><div style='float: left;'><a href='http://www.google.com/chrome' target='_blank' title='Get current Google Chrome'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get current Google Chrome' /></a></div></div></div>
[ELSE]
    lib.oldIE = TEXT
    lib.oldIE.value =
[GLOBAL]
